[package]
name = "static_hash_set"
version = "0.1.0"
edition = "2024"

[features]
diffie = []
floyd = []

[dependencies]
cuckoofilter = "0.5.0"
fastbloom = "0.14.0"
fxhash = "0.2.1"
hashbrown = { path = "../ext/hashbrown" }
mem_dbg = { version = "0.3.0", features = ["derive"] }
memsize = "0.1.4"
prefetch-index = "0.2.0"
rand = "0.9.2"
rustc-hash = "2.1.1"
sux = "0.14.0"
wide = "0.7.33"
kphf.path = "../kphf"
fph-table-sys = { path = "../ext/fph-table-sys" }
mapembed-sys = { path = "../ext/mapembed-sys" }
engineering-kphf = { path = "../ext/engineering-kphf" }
csv = "1.4.0"
serde = "1.0.228"
ptr_hash = "2.0.0-alpha.1"
ph = "0.11.0"
seedable_hash = { version = "0.2.3", features = ["gxhash"] }
gxhash = "3.5.0"
