[package]
name = "static_hash_set"
version = "0.1.0"
edition = "2024"

[features]
default = ["kphf", "bench"]
diffie = []
floyd = []

kphf = ["dep:kphf"]
bench = ["dep:hashbrown", "dep:ph", "dep:ptr_hash", "dep:fph-table-sys"]

# Enable external rust-based hash set implemenations in the library.
ext = ["dep:fastbloom", "dep:cuckoofilter"]

# Enable external c-based hash set implemenations in the benchmarks.
extc = ["dep:mapembed-sys", "dep:engineering-kphf"]

[dependencies]
fxhash = "0.2.1"
mem_dbg = { version = "0.4.3", features = ["derive"] }
memsize = "0.1.4"
prefetch-index = "0.2.0"
rand = "0.10.2"
rustc-hash = "2.1.1"
wide = "1.5.0"
csv = "1.4.0"
serde = { version = "1.0.228", features = ["serde_derive"] }
seedable_hash = { version = "0.2.3", features = ["gxhash"] }
gxhash = "3.5.0"

kphf = { path = "../kphf", optional = true }

hashbrown = { path = "../ext/hashbrown", optional = true }
ph = { version = "0.11.0", optional = true }
ptr_hash = { version = "2.0.0-alpha.1", optional = true }
fastbloom = { version = "0.17.0", optional = true }
cuckoofilter = { version = "0.5.0", optional = true }

fph-table-sys = { path = "../ext/fph-table-sys", optional = true }
mapembed-sys = { path = "../ext/mapembed-sys", optional = true }
engineering-kphf = { path = "../ext/engineering-kphf", optional = true }
rayon = "1.12.0"
