bench:
    cargo run -r | tee eval/data.csv
plot:
    cd eval && python plot.py laptop diffie floyd

bench_diffie:
    sbatch --partition=diffie --wrap='cargo run -r -F diffie | tee eval/data-diffie.csv'
bench_floyd:
    sbatch --partition=floyd --wrap='cargo run -r -F floyd | tee eval/data-floyd.csv'

